### ISSUE TITLE
Remove the PSystemMemorial or at the very least make it an option

### ISSUE THREAD

**Issue by Johnlon** [Banno/sbt-plantuml-plugin#7]
The presence of this feature appears to users of the Wiki as a defacement/hack of some sort.

https://github.com/Banno/sbt-plantuml-plugin/blob/master/src/main/java/net/sourceforge/plantuml/eggs/PSystemMemorial.java

**Comment by adamdecaf** [comment]
Wow, I didn't know that was in there. There's an upstream issue about this too: https://github.com/plantuml/plantuml/issues/25 

I'll release 1.1.2 today with it removed.

**Comment by adamdecaf** [comment]
`1.1.2` should be released on bintray. can you try it out? Thanks!
